### ISSUE TITLE
Bug with two commands running simultaneously in different channels

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/MissionAlertBot#125]
I was using carrier_edit in bot-commands while McKee used carrier_list in carrier-training and the carrier_edit command was (incorrectly) taking input from carrier-training. Is this an issue with any two commands running simultaneously or can we work around it without limiting all commands to the same channel?

**Comment by gcruicks** [comment]
Issue happened again today, not sure what the problem is, but it might be that passing the context object is not the right solution here, even though it makes things much cleaner.

**Comment by gcruicks** [comment]
https://discord.com/channels/800080948716503040/802523724674891826/848223638934650922

**Comment by gcruicks** [comment]
Suggest we add logging on what the context objects memory ID are when using them, then we can maybe see if it is being altered somewhere.

**Comment by gcruicks** [comment]
We could also just pass in the user directly to the sub-function, then use that for the comparison
