### ISSUE TITLE
Wing missions stock

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/MissionAlertBot#138]
**Add Wing Mining Mission (WMM) stock database `wmm.db` with fields:**

- carrier - full name of carrier pulled from carriers.db }
- cid - carrier reg pulled from carriers.db }
- channelid - carrier channelid pulled from carriers.db } this is all to avoid unnecessary cross-referencing with carriers.db - may not be needed
- commodity - commodity held
- amount - amount of commodity held
- system - system carrier is in
- station - station for missions
- discord_alert_id - the message ID for the carrier's stock in #wmm-stock

**Add commands:**

`m.stock <carrier> <commodity> <amount> <system> <station>`
Used by COs in #missiongenerator. Add a stock entry for a carrier in the db and broadcast alert in #wmm-stock if no previous matching entries in db for that carrier, or update alert if previous matching entries found.

If stock entry already exists for that carrier/commodity then:

- don't require system/station args
- update amount in db
- update alert in #wmm-stock

`m.t` and alias `m.empty`, `/empty`?
Use by anyone in a carrier's channel to mark stock empty. Search through db and return all matching commodities (i.e. parse all entries with matching carrier channel id), ask user which commodity is empty. (Allow multiple answers?) Update alert in #wmm-stock if entries for carrier channel remain, delete if no more entries for carrier channel remain

`/share`
Use in carrier's channel or #wmm-discussion or #laser-death-barge-disco-parties to mark yourself as looking to share missions. Functions like /crew - detect which role to add / remove based on channel and user's existing role status.

**Comment by netchild** [comment]
does this include multiple commodities per carrier? what about marking one commoditiy empty when there are multiple? shall COs be able to update stock of FC of different CO? What If I want ot announce the sell price on the FC?

**Comment by gcruicks** [comment]
> does this include multiple commodities per carrier? 

Yes we need to handle multiple commodities

> what about marking one commoditiy empty when there are multiple? 

Yes

> shall COs be able to update stock of FC of different CO? 

I don’t see why not, you can do it with missions today already (ie you can run a mission for someone else)

> What If I want ot announce the sell price on the FC?

Not sure if this is really needed, based on the discussion yesterday, as long as the price is profitable does it really matter?
