### ISSUE TITLE
Carrier list overloaded

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/MissionAlertBot#14]
m.carrier_list embed only shows 25 carriers total (out of ~40) owing to field limit in Embeds

**Comment by gcruicks** [comment]
I will take this after we fix the pending PR for #10 as it provides the skeleton to do this already.

We can do this in a couple of ways, either with the emojis, or just directly to send the whole list once after the other. Emojis will be easier/more maintainable longer term
