### ISSUE TITLE
Change m.issions to only show number of active missions and a link to #trade-alerts when used by non COs

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/MissionAlertBot#15]
Requested some time ago but perhaps not needed now usage has died down. If implemented, functionality should remain when used by COs (Carrier Owners) but show abbreviated list when used by non COs.

**Comment by gcruicks** [comment]
@cimspin do we need an embed for this, or just a simple message back to the user works? How lazy can I get away with being?
