### ISSUE TITLE
Checking whether carrier is on a mission already can get confused when there are multiple partial name matches for a carrier

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/MissionAlertBot#151]
e.g. if Rasputin is on a mission you can't use m.load ras for Ras Tschubai

**Comment by gcruicks** [comment]
Maybe get the carrier first would be the easier option:

1. Get the full carrier details.
2. Check if carrier via full name is on a mission

**Comment by cimspin** [comment]
Fixed in #292
