### ISSUE TITLE
Create channel for FC during trade mission and delete it when mission is complete

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/MissionAlertBot#183]
- discord channel field in carriers DB should again just be the channel name as text string (as presently generated on carrier_add), called by mission creation to create a temporary channel with that name
- mission creation needs to create the channel, set permissions and store its ID in missions db
- mission completion should delete the channel (after a short delay? 5 minutes?)
- /info needs to resolve channel info from looking up its string in carriers db OR its id in missions db and cross ref with carriers
- all instances of links to carrier channels need to be removed from find commands OR checked to see if a mission is active then pulled from missions db
- send a direct message to COs when a message is complete as channel will be deleted

It's a big change.

**Comment by cimspin** [comment]
If there's a timer for deletion then there needs to be a check when a new mission is created to see if an old one is "cooling down" and then take over the existing channel and cancel its deletion.

**Comment by cimspin** [comment]
I wonder if having MAB prune old channels _when a new mission is created_ would be a more robust way of achieving this. It means old channels sit around for an unspecified amount of time but prevents issues with timers/async, and means that most channels should stick around for at least a few minutes unless someone is super unlucky

**Comment by cimspin** [comment]
`category = client.get_channel(id_here)

for channel in category.text_channels:
    await channel.delete()`

After `for` we can do a check to see if the channel being iterated to is in the mission db channel list of active missions?

**Comment by gcruicks** [comment]
Easiest would be to just have the channel blow itself up after n minutes post the completion. Is there any issue to have 2 channels for a carrier active at once? The only downside I can see is continuity between back to back trades

**Comment by gcruicks** [comment]
My idea would be:

M.complete
<bot announces channel deletion in n minutes>
Folks can do what they want
<bot nukes the channel>

**Comment by cimspin** [comment]
Been thinking about this and think we should do the timer thing but perhaps the timer could be stopped if a new mission starts with the same carrier and the same channel re-used. Just feels a bit more elegant.

**Comment by gcruicks** [comment]
That would work, we just need a time limit defined as the max value, and to ensure the deletion is thread safe in such a way that the deletion can’t occur, while a post is ongoing. Else you would have a risk of user posting a mission, we detect the channel exists, and then it gets deleted before we turn the timer off

**Comment by cimspin** [comment]
Have begun work on this
