### ISSUE TITLE
Track when a carrier last posted a mission and have a search to return a list of active carriers

### ISSUE THREAD

**Issue by gcruicks** [PilotsTradeNetwork/MissionAlertBot#200]
We are deprecating carrier channels, we need to track when a carrier last posted a mission to understand what is active and what is not.

We also need a search that takes the data, and returns sorted by date (newest to eldest?) the listing, so we understand how many carriers are currently active, where active is to be a defined terminology (maybe in the past 2 weeks?)

**Comment by Randomgazz** [comment]
Resolved? Last trade now tracked with roles managed.

**Comment by cimspin** [comment]
Gonna close this
