### ISSUE TITLE
Unbound variable error during mission generation

### ISSUE THREAD

**Issue by gcruicks** [PilotsTradeNetwork/MissionAlertBot#223]
m.load rainbow agro “ANLAVE” "Suri Park" 12 L 20k

Oh no! Something went wrong :( Mission generation aborted.
400 Bad Request (error code: 50035): Invalid Form Body
In name: This field is required
Sorry, that didn't work. Check your syntax and permissions, error: Command raised an exception: UnboundLocalError: local variable 'mission_temp_channel_id' referenced before assignment

**Comment by cimspin** [comment]
Carrier not found error needs to be added and the function stopped at that point, this was not caught and so fell through to next error caused by there being no assigned carrier
