### ISSUE TITLE
Feature: "Dry run" - get text without creating mission

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/MissionAlertBot#27]
Possibly an extra option for naked m.load/unload commands as proposed in issue #20

**Comment by cimspin** [comment]
Possibly related to #294

**Comment by skiedude** [comment]
Isn't this fulfilled by using the `t` option @cimspin ?

**Comment by cimspin** [comment]
> Isn't this fulfilled by using the `t` option @cimspin ?

Sure is!
