### ISSUE TITLE
Add shortname and owner name to trade alerts

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/MissionAlertBot#289]
For use with ;stock shortname, as footer maybe?

**Comment by skiedude** [comment]
![tradealert](https://user-images.githubusercontent.com/6210395/196572086-6aead323-bc7f-4a9b-b189-493cde1fbcd1.png)
@cimspin looks like `;stock shortname` is there, I think the only thing missing would be the owners name somewhere. Would it be better to have it in the footer?
or perhaps we ping the owners in the message the bot posts as a follow up
`@Hauler: ptn-justified loading Silver from VIRTANEN HUB station in system BRANI : 20k per unit profit : 19k demand : L-pads.`

Would turn into 
`@Hauler: ptn-justified loading Silver from VIRTANEN HUB station in system BRANI : 20k per unit profit : 19k demand : L-pads. Contact @ownerping for questions`

**Comment by TuggyBoat** [comment]
I'm almost wondering if we could do away with using the shortname in the carrier's channel and use a back-end marker based off the channel itself.

**Comment by cimspin** [comment]
I put stock info in a while back and didn't reference the issue, whoops. Let's close this and open a new issue for ownername.

**Comment by cimspin** [comment]
I put stock info in a while back and didn't reference the issue, whoops. Let's close this and open a new issue for ownername.
