### ISSUE TITLE
Training mode 🤔 

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/MissionAlertBot#294]
A version of the mission generator triggered by users with the Trainee role which doesn't take any actual actions with channels/pings/etc?

**Comment by cimspin** [comment]
Alternatively triggered in dedicated training channel. Post all results to the channel instead of "live" destinations

**Comment by Randomgazz** [comment]
This was suggested again as part of the onboarding improvements.

**Comment by cimspin** [comment]
Training channel that accepts mission commands but if commands are in said channel sends output to same channel?
Would training mode still put an entry in the mission database?
Or can they just use the "t" option in the existing channel, which now no longer generates a mission?

**Comment by Randomgazz** [comment]
I feel a 'sandbox' channel would be the most comfortable for trainees, with real mission generation locked behind training completion. Could have even more complex training scenarios to test EDMC off etc during onboarding. Database might be needed to allow closing of test missions?
