### ISSUE TITLE
Graceful response when nominations not found for a user

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/MissionAlertBot#309]
Using m.nom_details with the ID of a user who has not been nominated should return a helpful response.

**Comment by skiedude** [comment]
![nomination](https://user-images.githubusercontent.com/6210395/196074340-29e53ebb-c52a-4d4c-b607-5caff40a18e4.png)

It felt strange to me to have it be the green embed when it didn't find any nominations, so I tried it out with:
`EMBED_COLOUR_REDDIT` - Red
`EMBED_COLOUR_WARNING = 0xFFD966         # yellow` - Yellow (new)

Any thoughts on which color scheme feels the best here? I personally like yellow (or some form of yellow) as its not a failure, but not a success.

**Comment by cimspin** [comment]
For now use `EMBED_COLOUR_ERROR` as that's the general "no/stop/nothing/don't/whoops" colour we've got presently. Diversifying to include a "warning" colour isn't a bad idea though, you could raise an issue for it seperately.
