### ISSUE TITLE
Command for COs to move their carriers between categories

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/MissionAlertBot#32]
https://stackoverflow.com/questions/64200134/renaming-and-moving-channel-to-a-different-category-with-a-command

Looks like ordering would be a PITA but if we're happy for it to no longer be alphabetical (which, honestly, it barely is anyway), then this looks simple.

**Comment by gcruicks** [comment]
Once we understand the new channel schema we will see if this is needed

**Comment by gcruicks** [comment]
Not required since we are removing carrier channels with #199
