### ISSUE TITLE
Restart command

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/MissionAlertBot#371]

**Comment by gcruicks** [comment]
Have a look at how booze bot does it I. The update command (that does not update anything … )

https://github.com/PilotsTradeNetwork/BoozeBot/blob/d25f576009d273fdce3bf1be7b7bf4921dc9533a/ptn/boozebot/commands/DiscordBotCommands.py#L114

it’s hacky, but it seems to work
