### ISSUE TITLE
Include carrier owner in Discord channel trade alert.

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/MissionAlertBot#393]
Ideally after the @Hauler ping line. Something like:
`This Trade Mission is run by @owner.`
Don't necessarily want to encourage users to ping unecessarily especially when the stock and m.complete commands exist, but we should have the owner name more visible.

**Comment by TuggyBoat** [comment]
Store the owner's Discord ID and do a nickname call would be the best without pinging, it wouldn't update if they updated their name however.

**Comment by cimspin** [comment]
> Store the owner's Discord ID and do a nickname call would be the best without pinging, it wouldn't update if they updated their name however.

We already store the ownerid in the carriers database. To do it without pinging could either use an embed (embeds don't ping) or an edit-after-sending technique like AdRoomba uses for Contractor pings
