### ISSUE TITLE
Need to differentiate between 'Legacy' and 'Live' Galaxies for trades

### ISSUE THREAD

**Issue by Randomgazz** [PilotsTradeNetwork/MissionAlertBot#404]
Needs to allow for trade missions to be split by galaxy
Split on both discord and Reddit needed

**Comment by Randomgazz** [comment]
This may also require the database to accept two carriers with the same name and ID if the owner chooses to maintain and trade with both versions. Flags or ID suffix for legacy carriers? Removing duplicate trade protection could be short term fix.

**Comment by cimspin** [comment]
Add commands:
`m.loadlegacy`
`m.unloadlegacy`

Add channels for legacy alerts:
live `1047113504332709938`
test `1047113662743183410`

Add prefix text for legacy alerts to Reddit and Discord:
`**◄ LEGACY UNIVERSE ►**:`

Branch PR-404

**Comment by cimspin** [comment]
Wine Loading needs a legacy channel too

**Comment by cimspin** [comment]
> Add commands: `m.loadlegacy` `m.unloadlegacy`
> 
> Add channels for legacy alerts: live `1047113504332709938` test `1047113662743183410`
> 
> Add legacy hauler role: live `1047133548886364190` test `1047152762707787786`
> 
> Add prefix text for legacy alerts to Reddit and Discord: `**◄ LEGACY UNIVERSE ►**:`
> 
> Branch PR-404

This is all done

Still to do:
- remove ;stock text from legacy missions
- add LEGACY watermark to legacy mission images
- differentiate between legacy and live carriers?
- separate mission DB for legacy and live?

**Comment by skiedude** [comment]
Also consider:
* /info should reflect if its a live or legacy carrier, or both?
* /find should reflect if its a live or legacy carrier, or both?
* /mission should be clear if its a live or legacy mission
* /missions should differentiante how many of each mission there is (legacy unloads, live unloads etc)
