### ISSUE TITLE
Logic to recreate the commodity database table

### ISSUE THREAD

**Issue by gcruicks** [PilotsTradeNetwork/MissionAlertBot#50]
We have a commodity data table today in the carrier dB, we need to be able to recreate this if any failures, and periodically reload the dB with new data from a source

**Comment by cimspin** [comment]
We could import EDDB's [https://eddb.io/archive/v6/commodities.json](url) (or import from it directly without a local copy?) and use it without any further processing. I tried and failed to use a json for the original carriers database but I'm not against it in principle!
