### ISSUE TITLE
Add Robot Overlords role to Nominate command blacklist

### ISSUE THREAD

**Issue by TuggyBoat** [PilotsTradeNetwork/MissionAlertBot#573]
https://github.com/PilotsTradeNetwork/MissionAlertBot/blob/801cdde1e178d4fd71140c9ec4c5701821278bd9/ptn/missionalertbot/botcommands/GeneralCommands.py#L507C9-L515C36

Role id: 802523214809923596

**Comment by cimspin** [comment]
Resolved in #574
