### ISSUE TITLE
Webhook permissions not working properly in community channels

### ISSUE THREAD

**Issue by TuggyBoat** [PilotsTradeNetwork/MissionAlertBot#636]
- Mentor has channel permissions, but not webhook
- Neither Mentor nor channel owner can copy webhook URLs from the integrations tab
- Restore to discohook command doesn't work when un-archived

**Comment by cimspin** [comment]
These should be server-side issues:
- Discohook utils did not have webhooks/manage messages permissions in the category - fixed on server
- Mentor didn't have webhook permissions in the category - fixed on server
- Last one should also be fixed but could imply another permissions sync problem. Closing for now but if restored channels don't have the proper permissions we will need another workaround in MAB
